name: Build the website

on:
  push:
    branches:
      - main   # Triggers workflow on push to the main branch
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install uv
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.12

      # Install dependencies
      - name: Restore environment
        run: uv sync

      # Install mc
      - name: Install mc
        uses: hostwithquantum/setup-mc@main

      # Download data
      - name: Download data
        run: bash ./sspcloud/download_data.sh

      # Set up Quarto
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Render Quarto in uv virtual environment (HTML)
      - name: Render
        run: uv run quarto render

      # # Render Quarto in uv virtual environment (HTML)
      # - name: Render in ipynb
      #   run: uv run quarto render --to ipynb
        
      # Publish website
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
